services:
  db:
    build: ./database/
    environment:
      POSTGRES_PASSWORD: dai-shpaku
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data 
    networks:
      - dai-network
    healthcheck:
      test: ["CMD-SHELL","ls"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped


  bot:
    build: ./
    volumes:
      - ./photos:/usr/src/app/photos/
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dai-network
    restart: unless-stopped

networks:
  dai-network:
    driver: bridge
